global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "apigateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8084"]

  - job_name: "companymicro"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "configserver"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "JobMicro"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "reviewmicro"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: "serviceregmicro"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8761"]
